config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'omniauth_callbacks/email_confirm_for_oauth'
  end

  concern :votable do
    resources :votes, only: :create
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: %i[commentable votable], shallow: true do
    resources :answers, concerns: %i[commentable votable], only: %i[create update destroy] do
      patch 'best', on: :member
    end
  end

  resources :attachments, only: :destroy

  root to: 'questions#index'

  mount ActionCable.server, at: '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Attachable
  include Commentable
  include Votable

  belongs_to :user

  has_many :answers, dependent: :destroy

  validates :title, :body, presence: true
  validates :title, uniqueness: { case_sensitive: false }

  def best_answer
    answers.find_by(best_answer: true)
  end

  def best_answer=(params_hash)
    transaction do
      best_answer&.update!(best_answer: false)
      params_hash[:new_best_answer].update!(best_answer: true) if params_hash[:set_new] == 'true'
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :question, only: %i[show update destroy]
  before_action :build_answer_and_comment, only: :show
  before_action :pass_params_to_js, only: :show

  after_action :publish_question, only: :create

  respond_to :js, only: :update

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def new
    respond_with(@question = Question.new)
  end

  def create
    respond_with @question = current_user.questions.create(question_params), location: -> { root_path }
  end

  def show
    respond_with @question
  end

  def destroy
    @question.destroy if current_user.author_of? @question
    respond_with @question, location: -> { root_path }
  end

  def update
    @question.update(question_params) if current_user.author_of? @question
    respond_with @question
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: %i[id file _destroy])
  end

  def question
    @question ||= Question.find(params[:id])
  end

  def build_answer_and_comment
    @answer = Answer.new
    @comment = Comment.new
  end

  def pass_params_to_js
    gon.question_id = @question.id
    gon.question_user_id = @question.user.id
    gon.current_user_id = current_user&.id
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question_for_index',
        locals: { question: @question }
      )
    )
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_question.html.slim
.question
  h1 = question.title
  == render 'shared/rating', object: question
  p = question.body
  h3 Attached files:
  == render 'shared/attachments', object: question
  h3 Comments:
  == render 'shared/comments', object: question
  - if current_user&.author_of? question
    = simple_form_for question, remote: true do |f|
      h3 Edit your question:
      .edit_question-errors
      = f.input :title
      = f.input :body
      h4 Attachments:
      .new-attachments
        .new-attachment-add
          = link_to_add_association 'Add file', f, :attachments, partial: 'shared/attachment_fields'
      br
      = submit_tag 'Ok'
    .question-actions-bar
      = link_to 'Edit', '#', class: 'question-edit_link'
      '  |
      = link_to 'Delete', question_path(question), method: :delete

app/views/questions/_question_for_index.html.slim
.question
  h3
    |#
    = question.title
  p = question.body
  = link_to 'Show', question_path(question)
  - if question.answers.any?
    '  |
    span = "#{pluralize(question.answers.count, 'answer')}"
  '  |
  span
    'Rating:
    = question.rating

app/views/questions/index.html.slim
h1 Questions
.questions
  - if @questions.count.zero?
    p No data
  - else
    - @questions.each do |q|
      == render 'question_for_index', question: q

= button_to 'Ask question', new_question_path, method: :get

app/views/questions/new.html.slim
= simple_form_for @question, url: { action: 'create' } do |f|
  h1 Ask your question:
  = render 'shared/errors', object: @question
  = f.input :title
  = f.input :body
  br
  h3 Attachments:
  .attachments
    = f.simple_fields_for :attachments do |a|
    .attachment-add
      = link_to_add_association 'Add file', f, :attachments, partial: 'shared/attachment_fields'
  br
  = f.submit 'Ask'

br
= link_to 'back', root_path

app/views/questions/show.html.slim
== render @question

.answers
  .best-answer
    - @best_answer = @question.answers.find_by best_answer: true
    == render @best_answer, best: true if @best_answer
  == render @question.answers, best: false

= simple_form_for [@question, @answer], remote: true do |new_answer|
  .new_answer-errors
  = new_answer.input :body, label: 'Your answer:'
  h4 Attachments:
  .attachments
    .attachment-add
      = link_to_add_association 'Add file', new_answer, :attachments, partial: 'shared/attachment_fields'
  = submit_tag 'Add answer'

br
= link_to 'back', root_path

.answer-edit-form-tmp
  = simple_form_for @answer, url: answer_path(:temp), method: :patch, remote: true do |ans|
    .edit_answer-errors.errors
    = ans.input :body, label: 'Edit your answer:'
    h4 Attachments:
    .new-attachments
      .new-attachment-add
        = link_to_add_association 'Add file', ans, :attachments, partial: 'shared/attachment_fields'
    = submit_tag 'Ok'

.new_comment-form-tmp
  = simple_form_for @comment, url: question_comments_path(:temp), remote: true do |comment|
    .new_comment-errors.errors
    = comment.input :body, label: 'Comment:'
    = submit_tag 'Ok'
  

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  $(".alert").html("<%= j flash.now[:alert] %>");
  $(".notice").empty();

  $('.edit_question-errors').html("<%= j render 'shared/errors', object: @question %>");
<% else %>
  $(".alert").empty();
  $(".notice").html("<%= j flash.now[:notice] %>");

  $('.question-actions-bar').show()
  $('.edit_question').hide()

  $('.question>h1').html('<%= @question.title %>')
  $('.question>p').html('<%= @question.body %>')

  $('.question>.attachments').html("<%= j render 'shared/attachments', object: @question %>")
  $('.question>.simple_form.edit_question>.nested-fields').remove()
<% end %>