config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'omniauth_callbacks/email_confirm_for_oauth'
  end

  concern :votable do
    resources :votes, only: :create
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: %i[commentable votable], shallow: true do
    resources :answers, concerns: %i[commentable votable], only: %i[create update destroy] do
      patch 'best', on: :member
    end
  end

  resources :attachments, only: :destroy

  root to: 'questions#index'

  mount ActionCable.server, at: '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
    end
  end
end

app/views/shared/_attachment_fields.html.slim
.nested-fields
  = f.input :file
  = link_to_remove_association 'Delete', f

app/views/shared/_attachments.html.slim
ul.attachments
  - if object.attachments.any?
    - object.attachments.each do |a|
      li.attachment
        = link_to a.file.filename, a.file.url
        - if current_user&.author_of? object
          '  |
          = link_to 'remove', attachment_path(a), class: 'attachment_delete', method: :delete, remote: true
  - else
    span none

app/views/shared/_comments.html.slim
.comments
  ul
    - if object.comments.any?
      - object.comments.each do |comment|
        li = comment.body
  = link_to 'Add comment', '#', class: 'comments_add-new' unless current_user.nil?

app/views/shared/_errors.html.slim
- if object.errors.any?
  .errors
    h3 = "Validation #{'error'.pluralize(object.errors.count)}:"
    - object.errors.messages.each do |error_key, error_messages|
      .validation-error
        p = error_key
        ul
          - error_messages.each do |error_message|
            li = error_message

app/views/shared/_rating.html.slim
.rating
  h4 Rating:
  - if user_signed_in? && !current_user.author_of?(object)
    - rating_by_user = current_user.rating_of object
    = link_to '+', { controller: :votes, action: :create, vote_type: :up, value: 1, "#{object.class.name.underscore}_id": object.id }, method: :post, remote: true, data: { type: :json }, class: [:up, rating_by_user == 0 ? nil : rating_by_user > 0 ? 'chosen_link' : 'disabled_link']
    span = object.rating
    = link_to '-', { controller: :votes, action: :create, vote_type: :down, value: -1, "#{object.class.name.underscore}_id": object.id }, method: :post, remote: true, data: { type: :json }, class: [:down, rating_by_user == 0 ? nil : rating_by_user < 0 ? 'chosen_link' : 'disabled_link']
  - else
    span = object.rating