config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  devise_scope :user do
    post 'omniauth_callbacks/email_confirm_for_oauth'
  end

  concern :votable do
    resources :votes, only: :create
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: %i[commentable votable], shallow: true do
    resources :answers, concerns: %i[commentable votable], only: %i[create update destroy] do
      patch 'best', on: :member
    end
  end

  resources :attachments, only: :destroy

  root to: 'questions#index'

  mount ActionCable.server, at: '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Attachable
  include Commentable
  include Votable

  belongs_to :user
  belongs_to :question

  validates :body, presence: true
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :question, only: :create
  before_action :answer, only: %i[update destroy best]

  after_action :publish_answer, only: :create

  respond_to :js

  authorize_resource

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    @answer.save
    respond_with @answer
  end

  def destroy
    @answer.destroy if current_user.author_of? @answer
    respond_with @answer
  end

  def update
    @answer.update(answer_params) if current_user.author_of? @answer
    respond_with @answer
  end

  def best
    question = @answer.question
    return unless current_user.author_of? question
    respond_with(question.best_answer = { new_best_answer: @answer, set_new: params[:bool] })
  end

  private

  def question
    @question ||= Question.find(params[:question_id])
  end

  def answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: %i[id file _destroy])
  end

  def publish_answer
    return if @answer.errors.any?
    AnswersChannel.broadcast_to(@question, @answer.as_json(include: :attachments))
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .answer*{'data-answer-id': answer.id} style=('display: none' if !best && answer.best_answer?)
    h3 = best ? '#BestAnswer' : '#Answer'
    - if current_user&.author_of? @question
      - if best
        = link_to 'Unmark', best_answer_path(@best_answer, bool: false), class: 'answer_unmark-best', method: :patch, remote: true
      - else
        = link_to 'Mark', best_answer_path(answer, bool: true), class: 'answer_mark-as-best', method: :patch, remote: true
    == render 'shared/rating', object: answer
    p = answer.body
    h4 Attached files:
    == render "shared/attachments", object: answer
    h4 Comments:
    == render "shared/comments", object: answer
    - if current_user&.author_of? answer
      = link_to 'Edit', '#', class: 'answer_edit'
      '  |
      = link_to 'Delete', answer_path(answer), class: 'answer_delete', method: :delete, remote: true

app/views/answers/best.js.erb
<% if @answer.errors.present? %>
  $(".alert").html("<%= j flash.now[:alert] %>");
  $(".notice").empty();
<% else %>
  $(".alert").empty();
  $(".notice").html("<%= j flash.now[:notice] %>");
<% end %>

app/views/answers/best_answer.js.erb
<% if @new_best_answer&.errors.present? %>
  $(".alert").html("<%= j flash.now[:alert] %>");
  $(".notice").empty();
<% else %>
  $(".alert").empty();
  $(".notice").html("<%= j flash.now[:notice] %>");
<% end %>

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  $(".alert").html("<%= j flash.now[:alert] %>");
  $(".notice").empty();
  $('.new_answer-errors').html('<%= j render "shared/errors", object: @answer %>');
<% else %>
  $(".alert").empty();
  $('.new_answer-errors').empty();
  $(".notice").html("<%= j flash.now[:notice] %>");

  $('.answers').append('<%= j render @answer, best: false %>');
  $('#new_answer textarea#answer_body').val('');
  $('#new_answer>.attachments>.nested-fields').remove();
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
  $(".alert").html("<%= j flash.now[:alert] %>");
  $(".notice").empty();
<% else %>
  $(".alert").empty();
  $(".notice").html("<%= j flash.now[:notice] %>");
<% end %>

app/views/answers/update.js.erb
var answer = $('.answer[data-answer-id="<%= @answer.id %>"]');

<% if @answer.errors.present? %>
  $('.alert').html('<%= j flash.now[:alert] %>');
  $('.notice').empty();
  
  answer.find('.edit_answer-errors').html('<%= j render "shared/errors", object: @answer %>');
<% else %>
  $('.alert').empty();
  $('.notice').html('<%= j flash.now[:notice] %>');
  answer.find('.edit_answer-errors').empty();

  answer.find('p').text('<%= @answer.body %>');
  answer.find('.attachments').html('<%= j render "shared/attachments", object: @answer %>');
  answer.find('form').remove();
<% end %>